name: Check for Target Platform updates

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'
  push:
    branches:
      - master
    paths:
      - '**.target'


jobs:
  update:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/updateTarget.yml@master
    with:
      author: M2E Bot <m2e-bot@eclipse.org>
      path: 'target-platform'
    secrets:
      token: ${{ secrets.M2E_BOT_PAT }}
